### ISSUE TITLE
[ENHANCEMENT] Add Flexbox CSS and responsive sizes

### ISSUE THREAD

**Issue by DillonB07** [JBYT27/GitHub-User-Search#6]
Hi,

I think this would benefit a lot from Flexbox.
If you don't know anything about Flexbox, I'd really recommend this guide. It helped me A LOT and I'd still be trying to muddle through `absolute` and `relative` layouts without it.

Guide: https://flexbox-rwd.com/
If you want something free, then you should check out CSS-Tricks article: https://css-tricks.com/snippets/css/a-guide-to-flexbox/ though it is a little tricky to understand in my opinion.

If you want, I'd be happy to help with the CSS. *Making it responsive. I don't really know what to do with the background.*

**Comment by JBYT27** [comment]
Hey @DillonB07!

I see, so I know a little about flexbox, but what does it exactly do that would benefit this? Or like what is flexbox itself (generalized)?

Sure! I’ll invite you to the repo and repl, and maybe we can talk about this there.

**Comment by JBYT27** [comment]
I’ll leave this issue open for now.

**Comment by DillonB07** [comment]
> CSS Flexible Box Layout, commonly known as Flexbox, is a CSS 3 web layout model. It is in the W3C's candidate recommendation stage. The flex layout allows responsive elements within a container to be automatically arranged depending upon screen size.

Essentially you have a base div(it could be a body tag instead but it's better to use a div) that you make a flex container. Then, all of the elements inside are responsive so they'll change size to fit the viewport that's being used.

**Comment by DillonB07** [comment]
I'll work on some new CSS on a new branch.

**Comment by JBYT27** [comment]
Oh, ok. Sure! Thanks!

**Comment by DillonB07** [comment]
Running it locally and when I try to use the search functionality I get an error.

```zsh
Traceback (most recent call last):
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/main.py", line 37, in search
    return render_template(
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dillonbarnes/Downloads/GitHub-User-Search/templates/search.html", line 22, in template
    <div class="user">
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'user'
```

<img width="1049" alt="Screenshot 2021-11-07 at 16 23 41" src="https://user-images.githubusercontent.com/83948303/140653225-a45c020d-22af-416b-bd39-3f4b1f177ada.png">


Uploaded to the responsive-css branch. Any idea what the issue is? *I've not changed anything in `search.html` unless my formatter did.*

https://github.com/JBYT27/GitHub-User-Search/tree/responsive-css

**Comment by JBYT27** [comment]
Ah, I think that error may have come from the HTML/jinja thinking that the `class="user"` came from Python, and then its getting confused, or replacing that with this class `user`. I'll change the class name from user to something else (Or you can do it. I don't mind.)

**Comment by DillonB07** [comment]
Nevermind. Seems I accidentally moved a pair of `""`

**Comment by JBYT27** [comment]
Oh, okay. Nevermind then :)

**Comment by DillonB07** [comment]
Sorry!

**Comment by JBYT27** [comment]
No no, it's okay 👍
